name = "Bhavesh Basrani"
description = "Accomplished actor, captivating with versatility and charisma."
keywords = "Bhavesh Basrani, actor, filmography, awards, versatile performances, Bollywood"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "notSoldierocks.github.io"

[[sections]]
title = "Movies"
description = "Here are some of my movies"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Nightcrawler"
description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = " "
[[sections.items]]
title = "Brokeback Mountain"
description = "A groundbreaking romantic drama challenging societal expectations"
url = " "
[[sections.items]]
title = "Prisoners"
description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
url = " "

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = " "
[[sections.items]]
title = "IMDb"
url = " "
[[sections.items]]
title = "Wikipedia"
url = " "
[[sections.items]]
title = "Rotten Tomatoes"
url = " "
